# Generated by Django 6.0.4 on 2026-05-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worker',
            name='specialization',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
