# Generated by Django 6.0.4 on 2026-05-20 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_worker_experience_worker_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('duration', models.IntegerField()),
                ('STATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.ev_station')),
                ('USERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.users')),
            ],
        ),
    ]
