# Generated by Django 6.0.4 on 2026-05-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ev_station',
            name='logo',
            field=models.ImageField(upload_to='stations/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='photo',
            field=models.ImageField(upload_to='users/'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='photo',
            field=models.ImageField(upload_to='workers/'),
        ),
    ]
