# Generated by Django 6.0.4 on 2026-05-21 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_alter_ev_station_logo_alter_users_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='USERS',
            new_name='ev_users',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='STATION',
            new_name='station',
        ),
        migrations.RenameField(
            model_name='ev_station',
            old_name='USER',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='USER',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='USER',
            new_name='user',
        ),
    ]
