# Generated by Django 6.0.4 on 2026-05-21 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_rename_users_booking_ev_users_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ev_station',
            old_name='logo',
            new_name='photo',
        ),
    ]
