# Generated by Django 6.0.4 on 2026-05-23 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_rename_logo_ev_station_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ev_station',
            name='user',
        ),
    ]
