# Generated by Django 6.0.4 on 2026-07-28 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='station',
        ),
    ]
