# Generated by Django 6.0.4 on 2026-08-11 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0013_slot_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='status',
        ),
    ]
